config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :users, only: [:show, :index]
  resources :posts do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  mount_uploader :avatar, AvatarUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :password_confirmation, :username, :avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(params[:comment].permit(:username, :content))
    @comment.user_id = current_user.id
    @comment.post_id = @post.id
    @comment.save
    redirect_to post_path(@post)
  end

  def destroy
  @post = Post.find(params[:post_id])
  @comment = @post.comments.find(params[:id])
  if @comment.user_id == current_user.id
  @comment.destroy
end
  redirect_to post_path(@post)

end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]


  def index
    @posts = Post.all.order("created_at DESC")
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
        if @post.save
          redirect_to posts_path
        else
          render 'new'
        end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:post, :avatar)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :avatar)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password, :avatar)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
      @users = User.all.order("created_at DESC")
  end

  def show

    @user= User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:username, :avatar)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="">
  <p class="media">
    <div class="">
      <p>
      <strong><%= comment.user.username %>: </strong>
      <%= comment.content %>

      </p>
    </div>
    <%= link_to 'Delete', [comment.post, comment], method: :delete, data: {confirm: "Are you sure?" } %>
    <hr />
  </p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.user.comments.build]) do |f| %>
<div>
    <%= f.label :How_do_you_really_feel? %>
    <%= f.text_area :content %>
</div>
<div>
    <%= f.submit  %>
</div>
<%= link_to "Cancel", root_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KickzBlogg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification">
      <p class="notice"><%= notice %></p>
    </div>
    <% end %>
      <% if flash[:alert] %>
      <div class="notification">
       <p class="alert"><%= alert %></p>
     </div>
    <% end %>

    <nav class="navbar">
      <%= link_to root_path, class: "navi" do %>
      <h1 class="title large-hover">👇🏾 Wuder Those 👀</h1>
      <% end %>

      <% if user_signed_in? %>

      <p class="newone" style=" top: -36px; position: relative; ">
        <%= link_to 'Kickz of the Day', new_post_path, class: "postie large-hover" %>
      </p>
      <div class="Profile" style="display: inline-flex;padding: 15px 25px;position: relative;top: -45px;">
        <%= link_to "Profile", user_path(current_user), class: "large-hover" %>
      </div>
      <div class="Fellow-Sneakerheads" style="display: inline-flex;padding: 15px 25px;position: relative;top: -45px;">
        <%= link_to "Fellow SneakerHeads", users_path, class: "large-hover" %>
      </div>
      <div class="edit-info" style="display: inline-flex;padding: 15px 25px;position: relative;top: -45px;">
        <%= link_to "edit info", edit_user_registration_path(current_user), class: "large-hover" %>
      </div>
      <div class="signOut" style="display: inline-flex;padding: 15px 25px;position: relative;top: -45px;">
        <%= link_to 'sign-out', destroy_user_session_path, method: :delete, class: "large-hover" %>
      </div>
      <div class="individual"></div>
      <div class="userSign" ><strong>Hi <%= current_user.username %>!<%=image_tag current_user.avatar.url %></strong></div>
      <% else %>
      <div class="signin">
        <%= link_to "Sign-in", new_user_session_path, class: "large-hover" %>
      </div>
      <div class="signup">
      <%= link_to "Sign-up", new_user_registration_path, class: "large-hover" %>
      </div>


      <% end %>
    </nav>
    <nav>
      <p class="searchbox">
          <input type="text" name="" id='searchInput'>
          <button type="submit" name="" id='searchBtn'>Search</button>
        </p>
        <div class="large-hover"id="search"></div>
    </nav>
    <script>
      var config = {
        api_key: 'e11acbbd6ab5d18206c964517f6197a5',
        link_to_size: 'm'
      }
      function search(){
        $("#search").empty();
        $('#search').flickr(config).photosSearch({
          text: $("#searchInput").val(),
          per_page: 5
        })
  // empty search box on submit
    $('#searchInput').val("");
  // opens image in new tab on click
    setTimeout(function() {
      var ul = document.getElementsByClassName("flickr")[0];
      for (let k = 0; k < 5; k++) {
        ul.children[k].children[0].target = "_blank";
      }
    }, 1000);
      }
  // submits search on enter click
      $('#searchInput').keydown(function (e) {

   var key = e.which;
   if(key == 13)  // the enter key code
    { search();

    }
  });
      $("#searchBtn").on("click", search);
    </script>
    <%= yield %>
  </body>
  <footer class="footer">Wuder Those 👀 | Kobi 2018 ©️ </footer>
</html>

app/views/posts/_feed.html.erb
<h1 class="large-hover">Best site ever bitches🤬</h1>

<!-- CAROUSEL begins -->
<base src="assets/offwhite1.png">
<div id="carousel">
  <figure id="spinner">
    <%= link_to new_post_path, class: "postie" do %>
    <img src="assets/offwhite1.png" alt>
    <% end %>
    <img src="assets/1jays.png" alt>
    <img src="assets/presto.png" alt>
    <img src="assets/14jays.png" alt>
    <img src="assets/15brons.png" alt>
    <img src="assets/aw.png" alt>
    <img src="assets/coolgrey.png" alt=>
    <img src="assets/adidas.png" alt>
  </figure>
</div>
<span style="float:left" class="large-hover" onclick="galleryspin('-')">&lt;</span>
<span style="float:right" class="large-hover" onclick="galleryspin('')">&gt;</span>
<!-- carousel end -->

<% if user_signed_in? %>
<div class="postform">
<%= render 'posts/form' %>
</div>
<table>
<br>
  <tbody class="user-block">
    <br>
<% @posts.each do |post| %>
  <tr class="row">

    <p class="postby"><%=link_to post.user.username, user_path(post.user)%> </p>
    <p class="postie large-hover"><%= post.post %></P> <p class="large-hover"><%=link_to image_tag(post.avatar.url), post %>
    </p>
    <% if current_user && @post.user_id == current_user.id %>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
<% end %>

</tbody>
</table>
<br>
<% end %>
<br>

app/views/posts/_form.html.erb
<div class="edButtons section">

<%= form_for @post do |f| %>
    <div class="">
        <%= f.label :got_kickz? %>
        <%= f.text_area :post %>
    </div>
    <div class="">
      <%= f.label :lets_see_em  %>
      <%= f.file_field :avatar %>
    </div>
    <div>
        <%= f.submit  %>
    </div>
    <%= link_to "Cancel", root_path %>
<% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <%= render 'feed' %>
    </div>
  </div>
</section>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong> -
    <%= @post.user.username %></strong>
</p>
<div class="edButtons">
  <div class="postie">
   <%= @post.post %>
 </div>
  <div class="large-hover"><%= image_tag @post.avatar.url  %>
</div>
<% if current_user && @post.user_id == current_user.id %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to "delete", post_path(@post), method: :delete, data: {confirm: "Are you sure you want to delete this post"} %>
<% end %>
</div>
<div class="">
<%= link_to 'Home', posts_path %>
</div>
<section class="edButtons comments">

<div class="container">
  <h2 class=""><%= @post.comments.count %> Comments</h2>
  <%= render @post.comments %>
  <div class="comment-form">
    <hr />

  <h3 class="edButtons subtitle">Say something nice...or talk some 💩</h3>
  <%= render 'comments/form' %>

  </div>
</div>
</section>

app/views/users/index.html.erb
<h1>Fellow  SneakerHeads</h1>

<% @users.each do |user| %>
  <p class="sh large-hover">º
  <%= link_to user.username, user %><%=  %>
</p>

<% end %>



<h1> SneakerHeads (<%=@users.count %>)...growing</h1>

app/views/users/show.html.erb
<div class="profile-indi">
<%= @user.username %>'s Profile
<% if @user.avatar.url %>
<%= image_tag @user.avatar.url %>
<% end %>
</div>

  <div class="large-hover">
<% @user.posts.each do |post| %>
          <p class="large-hover"><%=link_to image_tag(post.avatar.url), post %></p>
         <p class="large-hover">- <%=link_to post.post, post %></p>
         <% if @user.id == current_user.id %>
         <div class="large-hover edButtons">
           <td class="editdelete"><%= link_to 'Edit', edit_post_path(post) %></td>
           <td class="editdelete"><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         </div>
</div>
       </tr>
     <% end %>
<% end %>